export const LOAD_ALL_LISTS_START = 'LOAD_ALL_LISTS_START';
export const LOAD_ALL_LISTS_SUCCESS = 'LOAD_ALL_LISTS_SUCCESS';
export const LOAD_ALL_LISTS_FAIL = 'LOAD_ALL_LISTS_FAIL';

// list
export const ADD_LIST = 'ADD_LIST';
export const INCREMENT_VOTER_COUNT = 'INCREMENT_VOTER_COUNT';

export const LOAD_LIST_START = 'LOAD_LIST_START';
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const LOAD_LIST_FAIL = 'LOAD_LIST_FAIL';
export const SET_USER_LIST_RANKINGS = 'SET_USER_LIST_RANKINGS';
export const UPDATE_LOCAL_SCORE = 'UPDATE_LOCAL_SCORE';

export const SET_USER = 'SET_USER';
export const SET_EXCLUSIONS = 'SET_EXCLUSIONS';
export const PUSH_EXCLUSIONS = 'PUSH_EXCLUSIONS';

export const POST_MATCHUP = 'POST_MATCHUP';

export const INSERT_ENTRIES = 'INSERT_ENTRIES';
export const PUSH_NEW_ENTRIES = 'PUSH_NEW_ENTRIES';
export const SET_IMAGE = 'SET_IMAGE';
export const DELETE_ENTRY = 'DELETE_ENTRY';

// auth
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';